name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  qa:
    strategy:
      matrix:
        php: [7.3]
    runs-on: ubuntu-latest
    container:
      image: wyrihaximusnet/php:${{ matrix.php }}-zts-alpine3.10-dev-root
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: composer install --ansi --no-progress --no-interaction --prefer-dist
      - name: 'Test'
        run: php tests/test.php
