name: Create Release
on:
  milestone:
    types:
      - closed
jobs:
  close-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.milestone.title }}
          release_name: ${{ github.event.milestone.title }}
          draft: false
          prerelease: false
