name: Generate
on:
  schedule:
    - cron:  '49 * * * *'
jobs:
  qa:
    runs-on: ubuntu-latest
    container:
      image: wyrihaximusnet/php:7.3-zts-alpine3.10-dev-root
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: composer install --ansi --no-progress --no-interaction --prefer-dist
      - name: Generate new version file
        id: generate
        run: php tools/generate.php
      - name: Test
        run: php tests/test.php
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.AUTH_TOKEN }}"
      - name: 'Get files changed since previous tag'
        id: fileschangedsinceprevioustag
        uses: "WyriHaximus/github-action-files-in-commit@master"
        with:
          baseSha: ${{ steps.previoustag.outputs.tag }}
          headSha: HEAD
        env:
          GITHUB_TOKEN: "${{ secrets.AUTH_TOKEN }}"
      - name: 'Get next minor version'
        id: semvers
        if: steps.fileschangedsinceprevioustag.outputs.files == ''
        uses: "WyriHaximus/github-action-next-semvers@master"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: 'Create new milestone'
        id: createmilestone
        if: steps.fileschangedsinceprevioustag.outputs.files == ''
        uses: "WyriHaximus/github-action-create-milestone@master"
        with:
          title: ${{ steps.semvers.outputs.patch }}
          description: ${{ env.PULL_REQUEST_BODY }}
        env:
          GITHUB_TOKEN: "${{ secrets.AUTH_TOKEN }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
          PULL_REQUEST_LABELS: Automated PR, New Version, automerge
          PULL_REQUEST_TITLE: "[New Version] Update versions file to PHP ${{ steps.generate.outputs.actual }}"
          PULL_REQUEST_BODY: "With the release of PHP ${{ steps.generate.outputs.actual }} this packages needs updating. So this PR will bump current to ${{ steps.generate.outputs.current }} and future to ${{ steps.generate.outputs.future }}."
          PULL_REQUEST_MILESTONE: ${{ steps.createmilestone.outputs.number }}
